#pragma once

#define PACKET_CAPACITY 300

enum class ServerMsgType {
	SERVER_REPLY_REGISTER_UP,
	SERVER_REPLY_LOG_IN,
	SERVER_REPLY_MODIFY_USER_INFO,
	SERVER_REPLY_FIND_USER,
	SERVER_REPLY_ADD_FRIEND,
	SERVER_REPLY_REMOVE_FRIEND,
	SERVER_REPLY_FIND_GROUP,
	SERVER_REPLY_ADD_GROUP,
	SERVER_REPLY_REMOVE_GROUP,
	SERVER_REPLY_GET_GROUP_MEMBERS,
	SERVER_REPLY_CREATE_GROUP,
	SERVER_REPLY_MODIFY_GROUP_INFO,
	SERVER_REPLY_PRIVATE_CHAT,
	SERVER_REPLY_GROUP_CHAT,
	SERVER_NOTICE_NEW_FRIEND,
	SERVER_NOTICE_REMOVE_FRIEND,
	SERVER_FORWARD_PRIVATE_CHAT,
	SERVER_FORWARD_GROUP_CHAT,
};

enum class ClientMsgType {
	REGISTER_UP,
	LOG_IN,
	MODIFY_USER_INFO,
	FIND_USER,
	ADD_FRIEND,
	REMOVE_FRIEND,
	FIND_GROUP,
	ADD_GROUP,
	REMOVE_GROUP,
	GET_GROUP_MEMBERS,
	CREATE_GROUP,
	MODIFY_GROUP_INFO,
	PRIVATE_CHAT,
	GROUP_CHAT,
};